import{a as q,i as s,S as v}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const w="https://pixabay.com/api/",E="49565039-11a2922cd8e7ceae59523da99",A=15;async function m(e,r){try{console.log("Searching for:",e);const o=await q.get(w,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:A}});return console.log("Raw API response:",o.data),!o.data.hits||!Array.isArray(o.data.hits)||o.data.hits.length===0?(s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),{hits:[],totalHits:0}):{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){return console.error("Axios error:",o),s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),{hits:[],totalHits:0}}}const M=new v(".gallery a",{captionsData:"alt",captionsDelay:250});function y(e){const r=document.querySelector(".gallery"),o=e.map(({webformatURL:l,largeImageURL:t,tags:a,likes:n,views:b,comments:L,downloads:S})=>`<li class="gallery-item">
        <a href="${t}" class="gallery-link">
            <img src="${l}" alt="${a}"/>
        </a>
        <div class="description">
            <p><b>Likes:</b> ${n}</p>
            <p><b>Views:</b> ${b}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${S}</p>
        </div>
    </li>
    `).join("");r.insertAdjacentHTML("beforeend",o),M.refresh()}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(){document.querySelector(".loader").classList.add("visible")}function f(){document.querySelector(".loader").classList.remove("visible")}function H(){const e=document.querySelector(".load-more-btn");e.style.display="block"}function d(){const e=document.querySelector(".load-more-btn");e.style.display="none"}let c="",i=1,B=15,u=0;const T=document.querySelector(".form"),$=document.querySelector(".load-more-btn"),I=document.querySelector('input[name="search-text"]');d();T.addEventListener("submit",async e=>{if(e.preventDefault(),c=I.value.trim(),!!c){i=1,u=0,P(),d(),g();try{const{hits:r,totalHits:o}=await m(c,i);if(console.log("Total hits:",o),u=o,r.length===0){s.error({title:"Error",message:"No images found"});return}y(r),h(),p()}catch(r){console.log(r),s.error({title:"Error",message:"An error catched while finding images. Try again."})}finally{f()}}});$.addEventListener("click",async()=>{i+=1,g();try{const{hits:e}=await m(c,i);if(console.log("Full API Response:",e),e.length===0){s.info({title:"No more images",message:"No more images found for your request."}),d();return}y(e),h(),p()}catch(e){console.log("Error:",e),s.error({title:"Error",message:"An error catched while finding images. Try again."})}finally{f()}});function h(){const e=Math.ceil(u/B);i<e?H():(d(),s.success({title:"End of results",message:"All pictures have been loaded"}))}function p(){var r;const e=(r=document.querySelector(".gallery"))==null?void 0:r.lastElementChild;e&&setTimeout(()=>{e.scrollIntoView({behavior:"smooth",block:"start"})},700)}
//# sourceMappingURL=index.js.map
