import{a as S,i,S as q}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const w="https://pixabay.com/api/",v="49565039-11a2922cd8e7ceae59523da99",A=15;async function u(e,r){try{console.log("Searching for:",e);const o=await S.get(w,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:A}});return console.log("Raw API response:",o.data),!o.data.hits||!Array.isArray(o.data.hits)||o.data.hits.length===0?(i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),{hits:[],totalHits:0}):{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){return console.error("Axios error:",o),i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),{hits:[],totalHits:0}}}const M=new q(".gallery a",{captionsData:"alt",captionsDelay:250});function m(e){const r=document.querySelector(".gallery");r.innerHTML="";const o=e.map(({webformatURL:s,largeImageURL:t,tags:a,likes:l,views:p,comments:b,downloads:L})=>`<li class="gallery-item">
        <a href="${t}" class="gallery-link">
            <img src="${s}" alt="${a}"/>
        </a>
        <div class="description">
            <p><b>Likes:</b> ${l}</p>
            <p><b>Views:</b> ${p}</p>
            <p><b>Comments:</b> ${b}</p>
            <p><b>Downloads:</b> ${L}</p>
        </div>
    </li>
    `).join("");r.insertAdjacentHTML("beforeend",o),M.refresh()}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(){document.querySelector(".loader").classList.add("visible")}function y(){document.querySelector(".loader").classList.remove("visible")}function E(){const e=document.querySelector(".load-more-btn");e.style.display="block"}function d(){const e=document.querySelector(".load-more-btn");e.style.display="none"}let c="",n=1,f=15,h=0;const H=document.querySelector(".form"),$=document.querySelector(".load-more-btn"),B=document.querySelector('input[name="search-text"]');d();H.addEventListener("submit",async e=>{if(e.preventDefault(),c=B.value.trim(),!!c){n=1,h=0,P(),g();try{const{hits:r,totalHits:o}=await u(c,n);if(console.log("Hits array:",r),console.log("Total hits:",o),r.length===0)return;m(r);const s=Math.ceil(o/f);n<s&&E()}catch(r){console.log(r),i.error({title:"Error",message:"An error catched while finding images. Try again."})}finally{y()}}});$.addEventListener("click",async()=>{n+=1,g();try{const{hits:e}=await u(c,n);if(console.log("Full API Response:",e),e.length===0){i.info({title:"No more images",message:"No more images found for your request."}),d();return}console.log("Rendering gallery with hits:",e),m(e);const r=Math.ceil(h/f);n>=r&&(d(),i.success({title:"No more results",message:"All images have been loaded"}))}catch(e){console.log("Error:",e),i.error({title:"Error",message:"An error catched while finding images. Try again."})}finally{y()}});
//# sourceMappingURL=index.js.map
